//#region Dependencies
const express = require('express');
const session = require('express-session');
const config = require('./config/config.json');
const path = require('path');
const mysql = require('mysql');
const utils = require('./utils/utils');
const io = require('socket.io')(4000);
//#endregion


//#region setup
// Init app
const app = express()

// Set our views directory and engine
app.engine('ejs', require('ejs-locals'))

app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

app.use(express.static(path.join(__dirname, 'static')));
app.use(express.urlencoded());

// Set our express session
app.use(session({
    secret: config.session_secret,
    saveUninitialized: false,
    name: 'uniqueSessionID',
    resave: false
}));

utils.log(`Express app successfully set up!`)

// Connect to database
const con = mysql.createConnection({
    host: config.db_host,
    user: config.db_user,
    password: config.db_password,
    database: config.db_name,
});

con.connect((err) => {
    if (err) throw err;

    utils.log(`Database "${config.db_name}" connected!`)
});
//#endregion


//#region Express
app.get('/dashboard', (req, res) => {
    res.render('dashboard.ejs', {
        app_name: config.app_name,
        page: 'Dashboard',
        is_user_page: true,
    });
});

app.get('/chat', (req, res) => {
    res.render('chat.ejs', {
        app_name: config.app_name,
        page: 'Live Chat',
        is_user_page: false,
        client_data: req.session.client_data,
        session_id: req.session.session_id
    });
});

app.post('/chat', (req, res) => {
    req.session.client_data = req.body;

    let name = req.body.name;
    let email = req.body.email;
    let phone = req.body.phone;

    // Insert new session, and get the session id generated by it.
    let insert_sql = "INSERT INTO `whatsapp`.`sessions` (`id`, `client_name`, `client_email`, `client_phone`, `status`, `timestamp`) VALUES (DEFAULT, ?, ?, ?, ?, FROM_UNIXTIME(?));"
    con.query(insert_sql, [name, email, phone, "active", utils.get_timestamp().toString()], (err, result) => {
        if (err) throw err;

        let get_insert_sql = "SELECT LAST_INSERT_ID();"
        con.query(get_insert_sql, (err, result) => {
            if (err) throw err;
    
            // utils.log(res[0]["LAST_INSERT_ID()"]);
            req.session.session_id = result[0]["LAST_INSERT_ID()"];
    
            res.redirect("/chat");
        })
    })
});
//#endregion

//#region Socket
io.on('connection', (socket) => {
    socket.on("session-message", message_data => {
        let sql = "INSERT INTO `whatsapp`.`messages` (`id`, `session_id`, `body`, `sender`, `timestamp`) VALUES (DEFAULT, ?, ?, ?, FROM_UNIXTIME(?));";

        con.query(sql, [message_data.session_id, message_data.body, message_data.sender, message_data.timestamp], (err, res) => {
            if (err) throw err;
        })

        socket.broadcast.emit("display-message", message_data);
    })
})
//#endregion


//#region Listener
app.listen(config.port, () => {
    utils.log(`App running at port ${config.port}! http://localhost:3000/dashboard`);
});
//#endregion